   name: Deploy Hugo Site1
   on:
     push:
       branches: [ "master" ]  # 触发分支（通常为源码分支）
   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:



         - name: checkout
           uses: actions/checkout@v4
           with:
             submodules: recursive  # 若主题为子模块需启用
             fetch-depth: 0


         - name: Setup Hugo
           uses: peaceiris/actions-hugo@v3
           with:
             hugo-version: "0.128.0"  # 指定与本地一致的版本
             extended: true           # 若主题依赖扩展版需启用



         - name: Build Site
           run: hugo --minify --gc    # 启用压缩和垃圾清理



         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v4
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./public    # 静态文件输出目录
             publish_branch: master # 部署目标分支
      
         - name: Cache Hugo Modules
           uses: actions/cache@v3
           with:
             path: ~/.cache/hugo_modules/
             key: ${{ runner.os }}-hugo-modules-${{ hashFiles('**/go.mod') }}
